name       : python-gobject2
version    : 2.28.6
release    : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/pygobject/2.28/pygobject-2.28.6.tar.xz : fb8a1d4f665130a125011659bd347c7339c944232163dbb9a34fd0686577adb8
license    : LGPL-2.1
component  : programming.python
summary    : PyGTK for GTK2 libraries
description: |
    PyGTK lets you to easily create programs with a graphical user interface using the Python programming language. The underlying GTK+ library provides all kind of visual elements and utilities for it and, if needed, you can develop full featured applications for the GNOME Desktop.
setup      : |
    %apply_patches
    %configure --disable-static --disable-introspection
build      : |
    %make
install    : |
    %make_install
